### ISSUE TITLE
"invalid date" error causes date column to be sorted incorrectly in the products page

### ISSUE THREAD

**Issue by pablofernandezorg** [blimpich/bmac-warehouse#79] opened 2019-03-04 09:33 UTC
Because some products have add dates and others dont, when I implemented the sorting algorithm the ones that dont have any data will show invalid date.

**Comment by blimpich** [comment] 2019-03-05 06:52
where do they get sorted in the list then? Do they float to the top or bottom? does it literally render as "invalid date" or is that in the console. Could you provide a screenshot?

**Comment by JulesChoq** [comment] 2019-04-09 17:50
@pablofernandezorg  need more info so we can either close this or fix it

**Comment by blimpich** [comment] 2019-04-10 06:26
After looking at the code base I understood what you were trying to say Pablo, so I renamed your issue. This should be resolved by simply floating the invalid dates to the bottom of the sorted list

**Comment by milloypr** [comment] 2019-04-30 04:13
Invalid dates are being caused by empty date fields, of which there are quite a few. I changed the sorting method to sort these to the bottom and also changed them to display as empty instead of "Invalid date". Issue should be taken care of.

**Closed by milloypr** 2019-04-30 04:13 UTC
